/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/layout/BottomNav.vue')['default']
    Carousel: typeof import('./src/components/common/Carousel.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    LoginModal: typeof import('./src/components/common/LoginModal.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastNotification: typeof import('./src/components/common/ToastNotification.vue')['default']
  }
}
